root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = ["date"]
  cmd = "go build -o ./tmp/main . && go test ./striver-a2z-dsa"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = [".gitignore","README.md","go.mod"]
  exclude_unchanged = true
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true 

[screen]
  clear_on_rebuild = true
  keep_scroll = true
